# Generated by Django 3.1.1 on 2021-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subject', models.CharField(max_length=10)),
                ('subjectName', models.CharField(max_length=70)),
                ('belongTo', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('name_group', models.IntegerField()),
            ],
        ),
    ]
