# Generated by Django 3.1.1 on 2021-03-29 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deparment',
            fields=[
                ('deparment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('deparment_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='belongTo',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='name_group',
        ),
        migrations.AlterField(
            model_name='subject',
            name='id_subject',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TimetableSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('midterm', models.BooleanField(blank=True)),
                ('finalterm', models.BooleanField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=60)),
                ('student_surname', models.CharField(max_length=60)),
                ('citizen_id', models.CharField(max_length=13)),
                ('birthday', models.DateField()),
                ('gpax', models.FloatField()),
                ('credit', models.IntegerField()),
                ('image_student', models.TextField()),
                ('deparment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.deparment')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='PreSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ManyToManyField(related_name='condition', to='regguide.Subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
    ]
