# Generated by Django 3.1.1 on 2021-03-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0002_auto_20210329_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionJSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.deparment')),
            ],
        ),
    ]
