# Generated by Django 3.1.1 on 2021-03-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0003_conditionjson_userlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
