# Generated by Django 3.1.1 on 2021-04-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0004_userlogin_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionjson',
            name='conditionJSON',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='RegisterSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
    ]
