# Generated by Django 3.1.1 on 2021-04-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0005_auto_20210403_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regguide.student'),
        ),
    ]
