# Generated by Django 3.1.1 on 2021-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0006_userlogin_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presubject',
            name='condition',
        ),
        migrations.AddField(
            model_name='presubject',
            name='condition',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
