# Generated by Django 3.1.1 on 2021-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0008_auto_20210417_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
