# Generated by Django 3.1.1 on 2021-04-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0009_student_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.deparment')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
    ]
