# Generated by Django 3.1.1 on 2021-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0011_auto_20210422_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='deparment',
            name='total_credit',
            field=models.IntegerField(null=True),
        ),
    ]
