# Generated by Django 3.1.1 on 2021-04-27 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0013_auto_20210422_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=200)),
                ('credit', models.IntegerField()),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.deparment')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.deparment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.groupsubject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regguide.subject')),
            ],
        ),
    ]
