# Generated by Django 3.1.1 on 2021-04-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0014_groupsubject_optionsubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='testsubject',
            name='room',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
