# Generated by Django 3.1.1 on 2021-05-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0015_auto_20210429_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registersubject',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
