# Generated by Django 3.1.1 on 2021-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0016_auto_20210503_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubject',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testsubject',
            name='yaer',
            field=models.IntegerField(null=True),
        ),
    ]
