# Generated by Django 3.1.1 on 2021-05-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regguide', '0018_auto_20210514_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='datesystem',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
